### PR TITLE
Spawn locations have been fixed in this pull request

### PR DESCRIPTION
**Pull request by nisathnasar**

### CODE REVIEW

**Review by hsravat-4590 — CHANGES_REQUESTED** [review]
In RoundManager, `TransformPlayersRound` all three methods have duplicated code which is unmaintainable. I think we can improve this by having a struct like:
```csharp
private struct RoundSpawnPosition{
    public Vector2 CopPosition;
    public Vector2 RobberPosition;
   //Add constructor if required
}
```
And then storing three instances of this in a list (one per round). Then, you can have one method which takes `int` param to specify a round or use a global value to determine which struct to use.

**Comment by nisathnasar** [comment]
> Round timer is set to 30 seconds currently

Changed it to 1m 30 seconds in a later commit

**Review by hsravat-4590 — CHANGES_REQUESTED** [review]
I'd put `RoundSpawnPosition` into a List. Then you won't need the switch statement with repeated code

**Comment by nisathnasar** [comment]
> I'd put `RoundSpawnPosition` into a List. Then you won't need the switch statement with repeated code

Do you mean like an array? like

`localPlayerRB.position = RoundSpawnPosition[roundNumber-1]`?

**Comment by hsravat-4590** [comment]
Either or

**Comment by nisathnasar** [comment]
> Either or But yeah the example you made pretty much captures it.

Check again pelase

**Review by hsravat-4590 — APPROVED** [review]

**Pull request merged**
