### PR TITLE
Optimise code in WeaponManager and PlayerHealth

### PR DESCRIPTION
**Pull request by hsravat-4590**
I've simplified the sound code in `WeaponManager` and condensed `enableComponents` and `disableComponents` into one method for `PlayerHealth`

### CODE REVIEW

**Review by ellimanh — CHANGES_REQUESTED** [review]
PlayerMovement audio can be optimised in the same way as WeaponManagers

**Comment by hsravat-4590** [comment]
> PlayerMovement audio can potentially be optimised in the same way as WeaponManager

Once I've finished with Rounds, I'll do that

**Review by ellimanh — APPROVED** [review]
👍

**Comment by hsravat-4590** [comment]
> PlayerMovement audio can potentially be optimised in the same way as WeaponManager
With PlayerAttack, there are two sources and the optimisation works around that. With PlayerMovement, there is only one so those optimisations are not necessary.

**Pull request merged**
